export const alphabet = [
  ['a', '🐝', 'abelha'],
  ['b', '🎂', 'bolo'],
  ['c', '🏠', 'casa'],
  ['d', '🦷', 'dente'],
  ['e', '🛝', 'escorregador'],
  ['f', '🔪', 'faca'],
  ['g', '🐈', 'gato'],
  ['h', '🦛', 'hipopótamo'],
  ['i', '⛪', 'igreja'],
  ['j', '🐞', 'joaninha'],
  ['k', '🥝', 'kiwi'],
  ['l', '✏️', 'lápis'],
  ['m', '🌽', 'milho'],
  ['n', '🚢', 'navio'],
  ['o', '👀', 'olhos'],
  ['p', '🤡', 'palhaço'],
  ['q', '🧀', 'queijo'],
  ['r', '🐀', 'rato'],
  ['s', '🚦', 'semáforo'],
  ['t', '🐢', 'tartaruga'],
  ['u', '🍇', 'uvas'],
  ['v', '🧹', 'vassoura'],
  ['w', '🧇', 'waffle'],
  ['x', '☕', 'xícara'],
  ['y', '🧘🏻', 'yoga'],
  ['z', '🦓', 'zebra']
]
